

%macro repetez(N1, N2);
%do i = 1 %to &N1;
	%if &i=1 %then %do; %let indep1=extfin1_sic2_1st_mktcap; %let indep2=extfin1_sic2_1st_priv; %end;
	%else %if &i=2 %then %do; %let indep1=extfin1_sic2_1st_mktcapln; %let indep2=extfin1_sic2_1st_privln; %end;
	%else %if &i=3 %then %do; %let indep1=extfin1_sic2_1st_mktcapln2; %let indep2=extfin1_sic2_1st_privln2; %end;
	%else %if &i=4 %then %do; %let indep1=extfin1_sic2_10_mktcap; %let indep2= extfin1_sic2_10_priv;  %end;
	%else %if &i=5 %then %do;%let indep1=extfin1_sic2_10_mktcapln; %let indep2= extfin1_sic2_10_privln;  %end;
	%else %if &i=6 %then %do;%let indep1=extfin1_sic2_10_mktcapln2; %let indep2= extfin1_sic2_10_privln2;  %end;
	%else %if &i=7 %then %do;%let indep1=extfin2_sic2_1st_mktcap; %let indep2= extfin2_sic2_1st_priv;  %end;
	%else %if &i=8 %then %do;%let indep1=extfin2_sic2_1st_mktcapln; %let indep2= extfin2_sic2_1st_privln;  %end;
	%else %if &i=9 %then %do;%let indep1=extfin2_sic2_1st_mktcapln2; %let indep2= extfin2_sic2_1st_privln2;  %end;
	%else %if &i=10 %then %do;%let indep1=extfin2_sic2_10_mktcap; %let indep2= extfin2_sic2_10_priv;  %end;
	%else %if &i=11 %then %do;%let indep1=extfin2_sic2_10_mktcapln; %let indep2= extfin2_sic2_10_privln;  %end;
	%else %if &i=12 %then %do;%let indep1=extfin2_sic2_10_mktcapln2; %let indep2= extfin2_sic2_10_privln2;  %end;
	%else %if &i=13 %then %do;%let indep1=exteqt1_sic2_1st_mktcap; %let indep2= extcrd1_sic2_1st_priv;  %end;
	%else %if &i=14 %then %do;%let indep1=exteqt1_sic2_1st_mktcapln; %let indep2= extcrd1_sic2_1st_privln;  %end;
	%else %if &i=15 %then %do;%let indep1=exteqt1_sic2_1st_mktcapln2; %let indep2= extcrd1_sic2_1st_privln2;  %end;
	%else %if &i=16 %then %do;%let indep1=exteqt1_sic2_10_mktcap; %let indep2= extcrd1_sic2_10_priv;  %end;
	%else %if &i=17 %then %do;%let indep1=exteqt1_sic2_10_mktcapln; %let indep2= extcrd1_sic2_10_privln;  %end;
	%else %if &i=18 %then %do;%let indep1=exteqt1_sic2_10_mktcapln2; %let indep2= extcrd1_sic2_10_privln2;  %end;
	%else %if &i=19 %then %do;%let indep1=exteqt2_sic2_1st_mktcap; %let indep2= extcrd2_sic2_1st_priv;  %end;
	%else %if &i=20 %then %do;%let indep1=exteqt2_sic2_1st_mktcapln; %let indep2= extcrd2_sic2_1st_privln;  %end;
	%else %if &i=21 %then %do;%let indep1=exteqt2_sic2_1st_mktcapln2; %let indep2= extcrd2_sic2_1st_privln2;  %end;
	%else %if &i=22 %then %do;%let indep1=exteqt2_sic2_10_mktcap; %let indep2= extcrd2_sic2_10_priv;  %end;
	%else %if &i=23 %then %do;%let indep1=exteqt2_sic2_10_mktcapln; %let indep2= extcrd2_sic2_10_privln;  %end;
	%else %if &i=24 %then %do;%let indep1=exteqt2_sic2_10_mktcapln2; %let indep2= extcrd2_sic2_10_privln2;  %end;
	%do j = 1 %to 2;
		%if &j=1 %then %do; %let control1=value_usd_rate; %end;
		%else %if &j=2 %then %do; %let control1=value_usd_rate2; %end;
		%do k = 1 %to &N2;
			%do l = 1 %to 12;
				%if &k=1 %then %do;
					%if &l=1 %then %do;		        %let dep= citanog_sic2crsp1; %let outsh="lhs1";  %end;
					%else %if &l=2 %then %do;		%let dep= patnog_sic2crsp1;  %let outsh="lhs2"; %end;
					%else %if &l=3 %then %do;		%let dep= rdsum;             %let outsh="lhs3"; %end;
					%else %if &l=4 %then %do;		%let dep= rdussum;           %let outsh="lhs4"; %end;
					%else %if &l=5 %then %do;		%let dep= orignog_sic2crsp1; %let outsh="lhs5"; %end;
					%else %if &l=6 %then %do;		%let dep= gennog_sic2crsp1;  %let outsh="lhs6"; %end;
					%else %if &l=7 %then %do;	    %let dep= citanog_sic2crsp1a; %let outsh="lhs7";  %end;
					%else %if &l=8 %then %do;		%let dep= patnog_sic2crsp1a;  %let outsh="lhs8"; %end;
					%else %if &l=9 %then %do;		%let dep= rdsuma;             %let outsh="lhs9"; %end;
					%else %if &l=10 %then %do;		%let dep= rdussuma;           %let outsh="lhs10"; %end;
					%else %if &l=11 %then %do;		%let dep= orignog_sic2crsp1a; %let outsh="lhs11"; %end;
					%else %if &l=12 %then %do;		%let dep= gennog_sic2crsp1a;  %let outsh="lhs12"; %end;
				%end;
				%else %if &k=2 %then %do;
					%if &l=1 %then %do;		        %let dep=citanog_isic2crsp1; %let outsh="lhs1";  %end;
					%else %if &l=2 %then %do;		%let dep= patnog_isic2crsp1; %let outsh="lhs2"; %end;
					%else %if &l=3 %then %do;		%let dep= rdsum; %let outsh="lhs3"; %end;
					%else %if &l=4 %then %do;		%let dep= rdussum;  %let outsh="lhs4"; %end;
					%else %if &l=5 %then %do;		%let dep= orignog_isic2crsp1; %let outsh="lhs5"; %end;
					%else %if &l=6 %then %do;		%let dep= gennog_isic2crsp1;  %let outsh="lhs6"; %end;
					%else %if &l=7 %then %do;	    %let dep= citanog_isic2crsp1a; %let outsh="lhs7";  %end;
					%else %if &l=8 %then %do;		%let dep= patnog_isic2crsp1a;  %let outsh="lhs8"; %end;
					%else %if &l=9 %then %do;		%let dep= rdsuma;             %let outsh="lhs9"; %end;
					%else %if &l=10 %then %do;		%let dep= rdussuma;           %let outsh="lhs10"; %end;
					%else %if &l=11 %then %do;		%let dep= orignog_isic2crsp1a; %let outsh="lhs11"; %end;
					%else %if &l=12 %then %do;		%let dep= gennog_isic2crsp1a;  %let outsh="lhs12"; %end;
				%end;
				%else %if &k=3 %then %do;
					%if &l=1 %then %do;		        %let dep=citanog_sic2otaf; %let outsh="lhs1";  %end;
					%else %if &l=2 %then %do;		%let dep= patnog_sic2otaf; %let outsh="lhs2"; %end;
					%else %if &l=3 %then %do;		%let dep= rdsum; %let outsh="lhs3"; %end;
					%else %if &l=4 %then %do;		%let dep= rdussum;  %let outsh="lhs4"; %end;
					%else %if &l=5 %then %do;		%let dep= orignog_sic2otaf; %let outsh="lhs5"; %end;
					%else %if &l=6 %then %do;		%let dep= gennog_sic2otaf;  %let outsh="lhs6"; %end;
					%else %if &l=7 %then %do;	    %let dep= citanog_sic2otafa; %let outsh="lhs7";  %end;
					%else %if &l=8 %then %do;		%let dep= patnog_sic2otafa;  %let outsh="lhs8"; %end;
					%else %if &l=9 %then %do;		%let dep= rdsuma;             %let outsh="lhs9"; %end;
					%else %if &l=10 %then %do;		%let dep= rdussuma;           %let outsh="lhs10"; %end;
					%else %if &l=11 %then %do;		%let dep= orignog_sic2otafa; %let outsh="lhs11"; %end;
					%else %if &l=12 %then %do;		%let dep= gennog_sic2otafa;  %let outsh="lhs12"; %end;
				%end;
				%else %if &k=4 %then %do;
					%if &l=1 %then %do;		        %let dep=citanog_isic2otaf; %let outsh="lhs1";  %end;
					%else %if &l=2 %then %do;		%let dep= patnog_isic2otaf; %let outsh="lhs2"; %end;
					%else %if &l=3 %then %do;		%let dep= rdsum; %let outsh="lhs3"; %end;
					%else %if &l=4 %then %do;		%let dep= rdussum;  %let outsh="lhs4"; %end;
					%else %if &l=5 %then %do;		%let dep= orignog_isic2otaf; %let outsh="lhs5"; %end;
					%else %if &l=6 %then %do;		%let dep= gennog_isic2otaf;  %let outsh="lhs6"; %end;
					%else %if &l=7 %then %do;	    %let dep= citanog_isic2otafa; %let outsh="lhs7";  %end;
					%else %if &l=8 %then %do;		%let dep= patnog_isic2otafa;  %let outsh="lhs8"; %end;
					%else %if &l=9 %then %do;		%let dep= rdsuma;             %let outsh="lhs9"; %end;
					%else %if &l=10 %then %do;		%let dep= rdussuma;           %let outsh="lhs10"; %end;
					%else %if &l=11 %then %do;		%let dep= orignog_isic2otafa; %let outsh="lhs11"; %end;
					%else %if &l=12 %then %do;		%let dep= gennog_isic2otafa;  %let outsh="lhs12"; %end;
				%end;
				%let ijk = %Eval(&k*1000+&j*100+&i);
				data framework_sic20to39_75_06_2; set intl.framework_75_06_2; if sic2 >= 20 and sic2 <= 39;run;
				options nonotes nosource nosource2 errors=0 nomerror noserror;
				proc printto print="D:\ifpatent\prg_win_yes\output.lst" new; run;
				%macro2i(&dep, &indep1, &indep2, &control1, export_us_rate, 1976, 2006, twoi&ijk, &outsh);
			%end;
		%end;
	%end;
%end;
%mend;
%repetez(24,4);
